FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY telemetry_mqtt.py .

RUN pip install --upgrade pip && pip install -r requirements.txt

# This container's main purpose is to run the telemetry script
ENTRYPOINT ["python3", "telemetry_mqtt.py"]