FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY drone_simulator.py .

RUN pip install --upgrade pip && pip install -r requirements.txt

# This container's main purpose is to run the simulator script
ENTRYPOINT ["python3", "drone_simulator.py"]